spring:
  application:
    name: bookings-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /bookmovies/api/v1
  port: 9050
eureka:
  client:
    serviceUrl:
      defaultZone: http:localhost:9010/eureka
