spring:
  application:
    name: showtimes-service
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:9020
        instance:
          name: Showtimes API Service
server:
  servlet:
    context-path: /bookmovies/api/v1
  port: 9080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

